CONSUMER_KEY: KRy7l0v8wex3w8Sy5zThai3Ea
CONSUMER_SECRET: X2eBm0Y21kYEuR74W3Frqc2JVIizOj8Q1EVGatDsEVVEJo0ucu
ACCESS_TOKEN_KEY: 1220032047516921859-otvXjhExyUTZ5GLxssc9h5ORqtPZja
ACCESS_TOKEN_SECRET: tmJKqM4ORfQW6CH7wIVV8uKNpmSEmeFAP8lYwGb19uYjj
service: pruebaZemoga

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  findUser:
    handler: index.handler
    events:
      - http:
          method: get
          path: user
          